#! /usr/bin/bash

(
cat <<- 'EOF'

<html>
<head>
<title>System Health Report</title>
</head>
<style>
body {
border: 5px solid black;
padding: 20px;
margin: 30px 500px;
}
table, th, td {
  border:1px solid black;
}
</style>
<body>
<h1>System Health Report</h1>

EOF
) > healthreport.html

current_date=$(date)

echo -e "<p>Generated on ${current_date}</p>\n<h2>CPU Usage - Last 5 Minutes</h2>" >> healthreport.html

free -h | awk 'BEGIN { print "<table><tr><th>Total</th><th>Used</th><th>Available</th><tr>" } NR > 1 { print "<tr><td>" $2 "</td><td>" $3 "</td><td>" $4 "</td></tr>" } END { print "</table>" }' >> healthreport.html

if [ $? -eq 0 ]; then
echo "Added memory report!"
else 
echo -e "<p>Could not generate memory report</p>" >> healthreport.html
fi

echo "<h2>Disk Usage Report</h2>" >> healthreport.html

df -h | grep /dev/nvme0n1p6 | awk 'BEGIN { print "<table><tr><th>Total</th><th>Used</th><th>Available</th></tr>" } { print "<tr><td>" $2 "</td><td>" $3 "</td><td>" $4 "</td></tr>" } END { print "</table>" }' >> healthreport.html


if [ $? -eq 0 ]; then
echo "Added Disk Usage report!"
else 
echo -e "<p>Could not generate disk usage report</p>" >> healthreport.html
fi

(
cat <<- 'EOF'

<p>Generated by 2022327</p>
<body>
</html>

EOF
) >> healthreport.html

mv healthreport.html index.html

docker build -t health-report .
docker run --name nginx-report -d -p 8080:80 health-report


 
